### ISSUE TITLE
Add link to nanosat-mo-framework project

### ISSUE THREAD

**Issue by gbonnefille** [ccsdsmo/ccsdsmo.github.io#3]
I recently discovered the project [nanosat-mo-framework](https://github.com/esa/nanosat-mo-framework). I think a link to such project could be added in this documentation.

**Comment by CesarCoelho** [comment]
Yap, please add the nanosat-mo-framework project to the website.

**Comment by ochurlaud** [comment]
@CaesarCoelho can you do a pull request with the project and a short description?
thx

**Comment by CesarCoelho** [comment]
Done:
https://github.com/ccsdsmo/ccsdsmo.github.io/compare/master...CesarCoelho:patch-1
